name: fspace
description: "Some examples about Flutter."
publish_to: 'none'

version: 1.0.0+100000000

environment:
  sdk: '>=3.4.4 <4.0.0'

# App运行时依赖
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 状态管理
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  riverpod_annotation: ^3.0.3

  # Model
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # 依赖注入
  get_it: ^9.2.0

  # 路由
  go_router: ^17.0.0

  # 类似Kotlin扩展方法
  dartx: ^1.2.0

  # 网络
  retrofit: ^4.9.1
  dio: ^5.9.0

  # 本地缓存
  shared_preferences: ^2.5.3

  # 事件总线
  event_bus: ^2.0.1

  # App包信息
  package_info_plus: ^9.0.0

  # 设备信息
  device_info_plus: ^12.3.0

  # uuid
  uuid: ^4.5.2

  # 加密
  crypto: ^3.0.7

  # Android 设备ID
  android_id: ^0.5.1

  # 视频播放
  video_player: ^2.10.1
  # cached_video_player_plus: ^4.0.4

  # 录音
  # record: ^6.1.2

  # 文件下载与缓存
  # flutter_cache_manager: ^3.4.1

  # 页面滑动控制
  # visibility_detector: ^0.4.0+2

  # iOS风格icon
  cupertino_icons: ^1.0.8

  # Toast
  bot_toast: ^4.1.3

  # 动画
  flutter_animate: ^4.5.2
  animations: ^2.1.1

  # Lottie支持
  lottie: ^3.3.2

  # SVG支持
  flutter_svg: ^2.2.3

  # 图片扩展
  extended_image: ^10.0.1

  # 测试停留在启动页
  flutter_native_splash: ^2.4.7

  # List Item滑动菜单
  # flutter_slidable: ^4.0.3

  # 短信验证码输入
  pinput: ^6.0.1

  # 扫码
  # mobile_scanner: ^7.1.3

  # 生成二维码
  # pretty_qr_code: ^3.5.0

  # iOS圆角
  figma_squircle_updated: ^1.0.1

  # 图片选择与剪裁
  pro_image_editor: ^11.14.0

  # 相册
  photo_manager: ^3.8.2

  # 保存图片到相册
  gal: ^2.3.2

  # 解压
  # flutter_archive: ^6.0.4

  # 虚线边框
  # dotted_border: ^3.1.0

  # 下拉刷新
  easy_refresh: ^3.4.0

  # 系统代理
  http_proxy: ^1.2.3

  # 瀑布流布局
  waterfall_flow: ^3.1.1

  # 权限管理
  permission_handler: ^12.0.1

  # webview
  webview_flutter: ^4.13.0
  webview_flutter_android:
  webview_flutter_wkwebview:

  # 打开超链接
  url_launcher: ^6.3.2

  # 相机
  # camera: ^0.11.3

  # 图片压缩
  flutter_image_compress: ^2.4.0

  # 路径提供者
  path: ^1.9.1
  path_provider: ^2.1.5

  # 底部弹窗
  # smooth_sheets: ^0.15.0

  # App评价
  # in_app_review: ^2.0.11

  # 跑马灯效果
  marquee: ^2.3.0

  # 支持多重的ScrollView
  # extended_nested_scroll_view: ^6.2.1

  # 个推一键认证
  getuiflut: ^0.2.40

  # 个推统一认证
  flutter_gysdk:
    path: plugins/flutter_gysdk

  # 微信登录
  # fluwx: ^5.7.5

  # Apple登陆
  sign_in_with_apple: ^7.0.1

  # 应用内购
  in_app_purchase: ^3.2.3
  in_app_purchase_android:
  in_app_purchase_storekit:

  # Firebase
  firebase_core: ^4.2.1

  # Firebase认证
  firebase_auth: ^6.1.2

  # Firebase统计
  firebase_analytics: ^12.0.4
  firebase_crashlytics: ^5.0.5

  # FaceBook统计
  facebook_app_events: ^0.21.0

  # Google登录
  google_sign_in: ^7.2.0

  # Google服务检查
  # google_api_availability: ^5.0.1

  # 数数统计
  thinking_analytics: ^3.3.1

  # AppsFlyer
  appsflyer_sdk: ^6.17.7+1

  # 时间格式化
  intl: ^0.20.2

  # 网络状态
  connectivity_plus: ^7.0.0

  # 软键盘处理
  flutter_keyboard_visibility: 6.0.0
  keyboard_actions: ^4.2.1

  # 多语言
  slang: ^4.11.0
  slang_flutter: ^4.11.0

  # ffmpeg
  # Android需要单独配置混淆
  # ffmpeg_kit_flutter_new: ^4.1.0

  # 视频提取关键帧
  # video_thumbnail: ^0.5.6
  
  # 屏幕截图
  # screenshot: ^3.0.0

  # 系统图片选择
  # image_picker: ^1.2.1

  # 异步扩展
  # async: ^2.13.0

  # sqlite数据库
  # sqflite: ^2.4.2

  # 本地缓存
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0

  # Google广告
  # google_mobile_ads: ^6.0.0

  # 本地消息推送
  # flutter_local_notifications: ^19.5.0
  
  # 简繁体转换
  # flutter_open_chinese_convert: ^0.7.0

  # 定位
  # location: ^8.0.1

  # Deep Links
  # app_links: ^7.0.0

  # 打开App设置
  # app_settings: ^7.0.0

  # 设备传感器
  # sensors_plus: ^7.0.0

  # 指南针
  # flutter_compass: ^0.8.1

  # 分享
  # share_plus: ^12.0.1

  # 滚动监听
  # scrollview_observer: ^1.26.2

  # Switch Button
  # animated_toggle_switch: ^0.8.5

  # 
  # percent_indicator: ^4.2.5

  # 
  # fl_chart: ^1.1.1

  #
  # shimmer: ^3.0.0

  #
  # like_button: ^2.1.0

  # App桌面角标
  # app_badge_plus: ^1.2.5

  #
  # just_audio: ^0.10.5

  # 
  # flutter_spinkit: 



# 开发时依赖
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # 静态检查
  flutter_lints: ^6.0.0
  custom_lint: ^0.8.1
  analyzer:

  # version code管理
  flutter_project_tool:
    path: 'tool/flutter_project_tool'

  # App图标生成
  flutter_launcher_icons: ^0.14.4

  # 模板代码生成
  build_runner: ^2.10.4
  flutter_gen_runner:

  # 状态管理模板代码生成、静态检查
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

  # retrofit注解生成
  retrofit_generator: ^10.2.0

  # Model相关
  json_serializable:
  freezed:

  # go_router路由
  go_router_builder: ^4.1.3

  # 多语言
  slang_build_runner: ^4.11.0

  # 缓存hive
  # hive_generator: ^2.0.1



# 依赖覆盖
dependency_overrides:



flutter:
  # 使用Material设计样式
  uses-material-design: true
  
  # 静态资源
  assets:
    - assets/images/
    - assets/lotties/
    - assets/svg/
    - assets/fonts/
    - assets/icon/

  # 字体配置
  fonts:
    - family: HarmonyOS Sans SC
      fonts:
        - asset: assets/fonts/HarmonyOS_Sans_SC_Black.ttf
          weight: 900
        - asset: assets/fonts/HarmonyOS_Sans_SC_Bold.ttf
          weight: 700
        - asset: assets/fonts/HarmonyOS_Sans_SC_Light.ttf
          weight: 300
        - asset: assets/fonts/HarmonyOS_Sans_SC_Medium.ttf
          weight: 500
        - asset: assets/fonts/HarmonyOS_Sans_SC_Regular.ttf
          weight: 400
        - asset: assets/fonts/HarmonyOS_Sans_SC_Thin.ttf
          weight: 100



# 运行 flutter pub run build_runner build 生成的image、fonts...指定保存在output路径下
# 图片通过 Assets.images.icLoginApple，字体通过 FontFamily.harmonyOSSansSC 访问
flutter_gen:
  output: lib/generated/
  line_length: 80



# App Icon生成
# 命令dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.jpeg"
  remove_alpha_ios: true
  